[package]
name = "executor"
version = "0.0.6"
authors = ["Richard Anaya"]
edition = "2018"
description = "A minimalistic async/await executor for web assembly"
license = "MIT OR Apache-2.0"
categories = ["wasm", "no-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
woke = "0.0.2"
spin = "0.5"
smallvec = "1.0.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]